name: build-release-on-main-push

on:
  push:
    branches:
      - main

jobs:
  build-release-on-main-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{secrets.PAT_DEPENDABOT_PR_AUTO_MERGE}}

      - name: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: maven-build-verify
        run: mvn --batch-mode --update-snapshots verify

      - uses: qoomon/actions--setup-git@v1
        with:
          user: actor

      - name: publish-on-maven-central
        run: mvn --batch-mode -P osslabz-release clean release:clean release:prepare release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}