name: release-notes-from-tag

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release-notes-from-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: create-release-notes
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true